### ISSUE TITLE
set up a biweekly meeting for organization-wide technical discussion

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [oceanmodeling/Management#5]

**Comment by brey** [comment]
Hi @zacharyburnettNOAA.

Since, I will be off between 21/2-26/2, we can schedule the first meeting sometime next week. Let me know which date/time works for you.

**Comment by zacharyburnettNOAA** [comment]
how is Wednesday afternoon, say 1 PM?

**Comment by brey** [comment]
It gets a bit late in Greece (for Panos). @pmav99 what do you think? Generally due to the time difference all days are good for us as long as it is not very late in the evening (our time). You should add +7 hours to EST. 

I am a bit constrained on Mon & Wed evenings but will make do if there is no other option.

**Comment by zacharyburnettNOAA** [comment]
> It gets a bit late in Greece (for Panos). @pmav99 what do you think? Generally due to the time difference all days are good for us as long as it is not very late in the evening (our time). You should add +7 hours to EST.

oh good point, I'm sorry I forgot to account for time zones. I am in EST (UTC-5), so I assume that Greece is the largest difference, but perhaps it might be beneficial to poll our time zones to find the best shared time of people who wish to meet

I'm definitely willing to meet earlier, probably as early as 8 AM EST (1 PM UTC)

**Comment by brey** [comment]
I guess we can do 10 AM (EST) that is 5PM (GR), 4PM (IT) which make it good enough for EU. Do you expect anyone west from your time zone?

**Comment by zacharyburnettNOAA** [comment]
that sounds like a reasonable time to me, I don't expect anyone west of that

**Comment by brey** [comment]
ok. Let's set it up for Wed 16/2 at 10 AM EST.

**Comment by brey** [comment]
@zacharyburnettNOAA Could you setup the invitation on Google meet because I am not sure we have permission to do it.

**Comment by zacharyburnettNOAA** [comment]
sure, here is the joining info:

> LNEC/VIMS/NOAA developers meeting
> Wednesday, February 16 · 10:00 – 11:00am
> Google Meet joining info
> Video call link: https://meet.google.com/eyy-zqbd-ppr
> Or dial: ‪(US) +1 208-715-5331‬ PIN: ‪260 201 088‬#
> More phone numbers: https://tel.meet/eyy-zqbd-ppr?pin=9418066551126

**Comment by brey** [comment]
I think we can close this one now.

**Comment by zacharyburnettNOAA** [comment]
meeting details:

Observational Data Collaboration
Wednesday, February 16 · 10:00 – 11:00am
Google Meet joining info
Video call link: https://meet.google.com/rvr-dnoh-iwy
Or dial: ‪(US) +1 319-382-9678‬ PIN: ‪388 031 212‬#
More phone numbers: https://tel.meet/rvr-dnoh-iwy?pin=8152807019250
